version: "3.8"

services:
  api:
    volumes:
      - ./api/src/:/app/src
      - ./api/data/a220-tech-docs:/app/data/a220-tech-docs
      - ./api/data/a220-non-conformities:/app/data/a220-non-conformities
    command: ["uvicorn", "src.app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"] 