version: '3.8'

services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
      target: prod
    image: ${REGISTRY}/${API_IMAGE_NAME}:${API_VERSION:-latest}
    ports:
      - "8000:8000"
    environment:
      - JWT_SECRET
      - JWT_EXPIRE
      - OPENAI_API_KEY
      - COHERE_API_KEY
      - TECH_DOCS_DIR
      - NC_DIR
      - RERANKING_ENABLED
    networks:
      - app-network

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./ui:/app
      - /app/node_modules
    environment:
      - VITE_API_URL
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./rpa/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - ui
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 