name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows:
      - Deploy API to Scaleway
    types:
      - completed
    branches:
      - master

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.workflow_run.head_sha }}

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: npm
        cache-dependency-path: ui/package-lock.json

    - name: Build UI with Makefile
      run: make ui-build
      env:
        BASE_PATH: '/${{ github.event.repository.name }}'
        VITE_API_URL: https://nc-api.sent-tech.ca

    - name: Upload static files as artifact
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: ui/build/

  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
